// <autogenerated>
//   This file was generated by T4 code generator SampleScriptTemplates.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

namespace SCEM.Model.Gl
{
  using System;
  using System.Collections.Generic;
  using System.Collections.Specialized;
  using SCEM.Model.Gl;
  using global::Glass.Mapper.Sc.Fields;
  using global::Glass.Mapper.Sc.Configuration;
  using global::Glass.Mapper.Sc.Configuration.Attributes;

  /// <summary>
  /// Represents a mapped type for item {A576808C-A294-44EB-9703-8FB2B66D985C} in Sitecore.
  /// Path: /sitecore/templates/SCEM/Pages/Base Page
  /// </summary>
  [SitecoreType(TemplateId = "{A576808C-A294-44EB-9703-8FB2B66D985C}")]
  public partial interface IBasePage : IBaseItem
  {
  }
}
